site_name: BOU-CP
docs_dir: src
site_url: https://boucp.github.io
use_directory_urls: false
repo_url: https://github.com/boucp/boucp.github.io
edit_uri: edit/master/src/
copyright: Text is available under the <a href="https://github.com/boucp/boucp.github.io/blob/master/LICENSE">Creative Commons Attribution Share Alike 4.0 International</a> License<br/>Copyright &copy; 2023 by <a href="https://github.com/boucp">https://github.com/boucp</a>
theme:
  name: material
  custom_dir: src/overrides
  font:
    text: Noto Sans Bengali
  palette:
  
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference 
  logo: favicon.ico
  favicon: favicon.ico
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tracking
    - navigation.tabs
    - toc.integrate
 #   - search.suggest
    - content.action.edit
    - content.code.copy

extra_javascript:
  - javascript/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
      tex_inline_wrap: ['$', '$']
      tex_block_wrap: ['$$', '$$']
  - pymdownx.highlight
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji 
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - meta

plugins:
  - mkdocs-simple-hooks:
      hooks:
          on_env: "hooks:on_env"
 # - search
  - tags:
      tags_file: tags.md
  - literate-nav:
      nav_file: navigation.md
  - git-revision-date-localized:
      enable_creation_date: true
      
  - git-committers:
      repository: boucp/boucp.github.io
      docs_path: src/
  
  - macros
extra:
  analytics:
    provider: google
    property: UA-267195013-1
 

